// Pixelblaze Pixel Mapper - Generated by LED Mapping Session
// Detected: 147 of 200 LEDs
// Original bounds: X=[290-962], Y=[277-679]
function (pixelCount) {
  var map = []
  map.push([0.1741, 0.1294]) // 0
  map.push([0.5, 0.5]) // 1 (not detected)
  map.push([0.5, 0.5]) // 2 (not detected)
  map.push([0.5, 0.5]) // 3 (not detected)
  map.push([0.5, 0.5]) // 4 (not detected)
  map.push([0.5, 0.5]) // 5 (not detected)
  map.push([0.5, 0.5]) // 6 (not detected)
  map.push([0.5, 0.5]) // 7 (not detected)
  map.push([0.5, 0.5]) // 8 (not detected)
  map.push([0.5, 0.5]) // 9 (not detected)
  map.push([0.5, 0.5]) // 10 (not detected)
  map.push([0.1354, 0.2363]) // 11
  map.push([0.5, 0.5]) // 12 (not detected)
  map.push([0.1339, 0.2363]) // 13
  map.push([0.1349, 0.2363]) // 14
  map.push([0.1225, 0.1360]) // 15
  map.push([0.1300, 0.1045]) // 16
  map.push([0.0670, 0.1343]) // 17
  map.push([0.5, 0.5]) // 18 (not detected)
  map.push([0.1369, 0.1086]) // 19
  map.push([0.0000, 0.2313]) // 20
  map.push([0.1354, 0.2363]) // 21
  map.push([0.1741, 0.1816]) // 22
  map.push([0.1731, 0.1343]) // 23
  map.push([0.1771, 0.1343]) // 24
  map.push([0.2004, 0.1418]) // 25
  map.push([0.2093, 0.1434]) // 26
  map.push([0.2068, 0.1517]) // 27
  map.push([0.2217, 0.1493]) // 28
  map.push([0.2078, 0.1277]) // 29
  map.push([0.2123, 0.1028]) // 30
  map.push([0.1786, 0.0920]) // 31
  map.push([0.5, 0.5]) // 32 (not detected)
  map.push([0.1811, 0.0837]) // 33
  map.push([0.1964, 0.0365]) // 34
  map.push([0.1905, 0.0182]) // 35
  map.push([0.1900, 0.0000]) // 36
  map.push([0.1781, 0.0116]) // 37
  map.push([0.5, 0.5]) // 38 (not detected)
  map.push([0.1518, 0.0373]) // 39
  map.push([0.5, 0.5]) // 40 (not detected)
  map.push([0.1225, 0.0498]) // 41
  map.push([0.5, 0.5]) // 42 (not detected)
  map.push([0.5, 0.5]) // 43 (not detected)
  map.push([0.5, 0.5]) // 44 (not detected)
  map.push([0.5, 0.5]) // 45 (not detected)
  map.push([0.0952, 0.0763]) // 46
  map.push([0.1002, 0.0837]) // 47
  map.push([0.5, 0.5]) // 48 (not detected)
  map.push([0.5, 0.5]) // 49 (not detected)
  map.push([0.1369, 0.1592]) // 50
  map.push([0.1339, 0.1219]) // 51
  map.push([0.1473, 0.1219]) // 52
  map.push([0.1691, 0.1269]) // 53
  map.push([0.1766, 0.1459]) // 54
  map.push([0.2009, 0.1418]) // 55
  map.push([0.2034, 0.1294]) // 56
  map.push([0.2202, 0.1443]) // 57
  map.push([0.2292, 0.1385]) // 58
  map.push([0.2455, 0.1294]) // 59
  map.push([0.5, 0.5]) // 60 (not detected)
  map.push([0.2500, 0.1036]) // 61
  map.push([0.2688, 0.1551]) // 62
  map.push([0.2862, 0.0995]) // 63
  map.push([0.5, 0.5]) // 64 (not detected)
  map.push([0.2852, 0.1617]) // 65
  map.push([0.2813, 0.1716]) // 66
  map.push([0.5, 0.5]) // 67 (not detected)
  map.push([0.2485, 0.2886]) // 68
  map.push([0.5, 0.5]) // 69 (not detected)
  map.push([0.5, 0.5]) // 70 (not detected)
  map.push([0.0938, 0.2330]) // 71
  map.push([0.5, 0.5]) // 72 (not detected)
  map.push([0.2401, 0.3400]) // 73
  map.push([0.1885, 0.2065]) // 74
  map.push([0.5, 0.5]) // 75 (not detected)
  map.push([0.1905, 0.2032]) // 76
  map.push([0.1830, 0.1957]) // 77
  map.push([0.1845, 0.2114]) // 78
  map.push([0.1850, 0.1965]) // 79
  map.push([0.1791, 0.1982]) // 80
  map.push([0.5, 0.5]) // 81 (not detected)
  map.push([0.1756, 0.1368]) // 82
  map.push([0.1766, 0.1294]) // 83
  map.push([0.1771, 0.1119]) // 84
  map.push([0.1801, 0.0896]) // 85
  map.push([0.1801, 0.0771]) // 86
  map.push([0.1806, 0.0721]) // 87
  map.push([0.1796, 0.0937]) // 88
  map.push([0.1751, 0.1260]) // 89
  map.push([0.1761, 0.1410]) // 90
  map.push([0.1726, 0.1667]) // 91
  map.push([0.5, 0.5]) // 92 (not detected)
  map.push([0.1250, 0.2496]) // 93
  map.push([0.5, 0.5]) // 94 (not detected)
  map.push([0.5, 0.5]) // 95 (not detected)
  map.push([0.2098, 0.3582]) // 96
  map.push([0.5, 0.5]) // 97 (not detected)
  map.push([0.1682, 0.1857]) // 98
  map.push([0.1682, 0.1841]) // 99
  map.push([0.8527, 0.2272]) // 100
  map.push([0.5, 0.5]) // 101 (not detected)
  map.push([0.5, 0.5]) // 102 (not detected)
  map.push([0.8229, 0.2189]) // 103
  map.push([0.8358, 0.2214]) // 104
  map.push([0.8338, 0.2189]) // 105
  map.push([0.5, 0.5]) // 106 (not detected)
  map.push([0.5, 0.5]) // 107 (not detected)
  map.push([0.8636, 0.2139]) // 108
  map.push([0.8690, 0.2156]) // 109
  map.push([0.5, 0.5]) // 110 (not detected)
  map.push([0.9286, 0.1318]) // 111
  map.push([0.8889, 0.3599]) // 112
  map.push([0.9340, 0.9826]) // 113
  map.push([0.5, 0.5]) // 114 (not detected)
  map.push([0.5, 0.5]) // 115 (not detected)
  map.push([0.5, 0.5]) // 116 (not detected)
  map.push([0.5, 0.5]) // 117 (not detected)
  map.push([0.9836, 0.2363]) // 118
  map.push([0.9906, 0.2388]) // 119
  map.push([1.0000, 0.2463]) // 120
  map.push([0.9985, 0.2595]) // 121
  map.push([0.9926, 0.9594]) // 122
  map.push([0.9559, 0.3060]) // 123
  map.push([0.9534, 0.3060]) // 124
  map.push([0.9444, 0.3060]) // 125
  map.push([0.5, 0.5]) // 126 (not detected)
  map.push([0.5, 0.5]) // 127 (not detected)
  map.push([0.9097, 0.2289]) // 128
  map.push([0.9072, 0.2264]) // 129
  map.push([0.5, 0.5]) // 130 (not detected)
  map.push([0.9107, 0.1368]) // 131
  map.push([0.8934, 0.1443]) // 132
  map.push([0.8859, 0.1426]) // 133
  map.push([0.8824, 0.1302]) // 134
  map.push([0.8656, 0.1061]) // 135
  map.push([0.8651, 0.0962]) // 136
  map.push([0.8601, 0.1144]) // 137
  map.push([0.8527, 0.1211]) // 138
  map.push([0.8497, 0.2015]) // 139
  map.push([0.8462, 0.1949]) // 140
  map.push([0.8512, 0.1194]) // 141
  map.push([0.8596, 0.1269]) // 142
  map.push([0.8651, 0.1310]) // 143
  map.push([0.8720, 0.1136]) // 144
  map.push([0.9077, 0.1393]) // 145
  map.push([0.9122, 0.1368]) // 146
  map.push([0.9286, 0.1310]) // 147
  map.push([0.5, 0.5]) // 148 (not detected)
  map.push([0.5, 0.5]) // 149 (not detected)
  map.push([0.9345, 0.2239]) // 150
  map.push([0.9018, 0.3060]) // 151
  map.push([0.9033, 0.3068]) // 152
  map.push([0.9097, 0.3101]) // 153
  map.push([0.9077, 0.3109]) // 154
  map.push([0.9008, 0.3068]) // 155
  map.push([0.9013, 0.3060]) // 156
  map.push([0.8983, 0.2579]) // 157
  map.push([0.8884, 0.2214]) // 158
  map.push([0.8879, 0.2214]) // 159
  map.push([0.8894, 0.2123]) // 160
  map.push([0.8780, 0.2189]) // 161
  map.push([0.8725, 0.2164]) // 162
  map.push([0.8681, 0.1849]) // 163
  map.push([0.8676, 0.1808]) // 164
  map.push([0.8646, 0.1609]) // 165
  map.push([0.8586, 0.1468]) // 166
  map.push([0.8497, 0.1542]) // 167
  map.push([0.8482, 0.1567]) // 168
  map.push([0.5, 0.5]) // 169 (not detected)
  map.push([0.5, 0.5]) // 170 (not detected)
  map.push([0.8452, 0.2214]) // 171
  map.push([0.8482, 0.2214]) // 172
  map.push([0.8676, 0.1642]) // 173
  map.push([0.9038, 0.1965]) // 174
  map.push([0.9018, 0.3085]) // 175
  map.push([0.9246, 0.2637]) // 176
  map.push([0.9206, 0.2620]) // 177
  map.push([0.9256, 0.2637]) // 178
  map.push([0.9023, 0.3085]) // 179
  map.push([0.5, 0.5]) // 180 (not detected)
  map.push([0.9033, 0.3060]) // 181
  map.push([0.9003, 0.3085]) // 182
  map.push([0.9405, 0.3151]) // 183
  map.push([0.9261, 0.3292]) // 184
  map.push([0.9365, 0.3035]) // 185
  map.push([0.9435, 0.3093]) // 186
  map.push([0.5, 0.5]) // 187 (not detected)
  map.push([0.9335, 0.2405]) // 188
  map.push([0.9003, 0.3433]) // 189
  map.push([0.9003, 0.3342]) // 190
  map.push([0.8988, 0.3209]) // 191
  map.push([0.8973, 0.3109]) // 192
  map.push([0.8770, 1.0000]) // 193
  map.push([0.8601, 0.9826]) // 194
  map.push([0.8348, 0.2529]) // 195
  map.push([0.8418, 0.9685]) // 196
  map.push([0.8130, 0.2222]) // 197
  map.push([0.5, 0.5]) // 198 (not detected)
  map.push([0.5, 0.5]) // 199 (not detected)
  return map
}
