// Pixelblaze Pixel Mapper - Generated by LED Mapping Session
// Detected: 228 of 300 LEDs
// Original bounds: X=[463-1275], Y=[51-714]
function (pixelCount) {
  var map = []
  map.push([0.9508, 0.0397]) // 0
  map.push([0.0316, 0.7905]) // 1
  map.push([0.5, 0.5]) // 2 (not detected)
  map.push([0.5, 0.5]) // 3 (not detected)
  map.push([0.8277, 0.5281]) // 4
  map.push([0.0546, 0.8161]) // 5
  map.push([0.0693, 0.8327]) // 6
  map.push([0.0657, 0.8583]) // 7
  map.push([0.5, 0.5]) // 8 (not detected)
  map.push([0.0903, 0.8899]) // 9
  map.push([0.1358, 0.8482]) // 10
  map.push([0.1650, 0.8910]) // 11
  map.push([0.1974, 0.8920]) // 12
  map.push([0.2257, 0.8774]) // 13
  map.push([0.2417, 0.8417]) // 14
  map.push([0.8650, 0.9271]) // 15
  map.push([0.4977, 0.5417]) // 16
  map.push([0.4834, 0.5367]) // 17
  map.push([0.4916, 0.5156]) // 18
  map.push([0.4990, 0.5231]) // 19
  map.push([0.3841, 0.7980]) // 20
  map.push([0.3845, 0.8146]) // 21
  map.push([0.4075, 0.7829]) // 22
  map.push([0.4017, 0.7784]) // 23
  map.push([0.3956, 0.8312]) // 24
  map.push([0.5, 0.5]) // 25 (not detected)
  map.push([0.3627, 0.8372]) // 26
  map.push([0.5, 0.5]) // 27 (not detected)
  map.push([0.5, 0.5]) // 28 (not detected)
  map.push([0.5, 0.5]) // 29 (not detected)
  map.push([0.3299, 0.8543]) // 30
  map.push([0.3032, 1.0000]) // 31
  map.push([0.2515, 0.9307]) // 32
  map.push([0.2963, 0.8447]) // 33
  map.push([0.2429, 0.7729]) // 34
  map.push([0.1748, 0.8628]) // 35
  map.push([0.1215, 0.7688]) // 36
  map.push([0.5, 0.5]) // 37 (not detected)
  map.push([0.1547, 0.7698]) // 38
  map.push([0.1284, 0.7678]) // 39
  map.push([0.1260, 0.7648]) // 40
  map.push([0.0927, 0.7724]) // 41
  map.push([0.5, 0.5]) // 42 (not detected)
  map.push([0.5, 0.5]) // 43 (not detected)
  map.push([0.5, 0.5]) // 44 (not detected)
  map.push([0.0480, 0.7894]) // 45
  map.push([0.0152, 0.7874]) // 46
  map.push([0.0000, 0.7090]) // 47
  map.push([0.0103, 0.7060]) // 48
  map.push([0.0386, 0.7241]) // 49
  map.push([0.0533, 0.7151]) // 50
  map.push([0.0730, 0.7136]) // 51
  map.push([0.0866, 0.7302]) // 52
  map.push([0.1075, 0.7302]) // 53
  map.push([0.1481, 0.7241]) // 54
  map.push([0.1851, 0.7136]) // 55
  map.push([0.2048, 0.7256]) // 56
  map.push([0.2380, 0.7508]) // 57
  map.push([0.2774, 0.7513]) // 58
  map.push([0.3057, 0.7407]) // 59
  map.push([0.3028, 0.7211]) // 60
  map.push([0.3377, 0.7080]) // 61
  map.push([0.3562, 0.7166]) // 62
  map.push([0.3722, 0.6789]) // 63
  map.push([0.5, 0.5]) // 64 (not detected)
  map.push([0.5, 0.5]) // 65 (not detected)
  map.push([0.5, 0.5]) // 66 (not detected)
  map.push([0.5, 0.5]) // 67 (not detected)
  map.push([0.5, 0.5]) // 68 (not detected)
  map.push([0.3082, 0.6910]) // 69
  map.push([0.5, 0.5]) // 70 (not detected)
  map.push([0.2844, 0.7015]) // 71
  map.push([0.5, 0.5]) // 72 (not detected)
  map.push([0.2552, 0.6910]) // 73
  map.push([0.5, 0.5]) // 74 (not detected)
  map.push([0.5, 0.5]) // 75 (not detected)
  map.push([0.5, 0.5]) // 76 (not detected)
  map.push([0.5, 0.5]) // 77 (not detected)
  map.push([0.1420, 0.6442]) // 78
  map.push([0.1543, 0.6332]) // 79
  map.push([0.1506, 0.6457]) // 80
  map.push([0.5, 0.5]) // 81 (not detected)
  map.push([0.5, 0.5]) // 82 (not detected)
  map.push([0.5, 0.5]) // 83 (not detected)
  map.push([0.0349, 0.5899]) // 84
  map.push([0.0324, 0.5955]) // 85
  map.push([0.0361, 0.5693]) // 86
  map.push([0.0464, 0.6045]) // 87
  map.push([0.0607, 0.6035]) // 88
  map.push([0.0636, 0.6060]) // 89
  map.push([0.0874, 0.5628]) // 90
  map.push([0.0915, 0.5990]) // 91
  map.push([0.1046, 0.6261]) // 92
  map.push([0.1395, 0.6095]) // 93
  map.push([0.1703, 0.6231]) // 94
  map.push([0.1838, 0.6216]) // 95
  map.push([0.2171, 0.6322]) // 96
  map.push([0.2491, 0.6322]) // 97
  map.push([0.2684, 0.6322]) // 98
  map.push([0.3008, 0.6201]) // 99
  map.push([0.3352, 0.6241]) // 100
  map.push([0.3172, 0.6216]) // 101
  map.push([0.3476, 0.6126]) // 102
  map.push([0.3365, 0.6171]) // 103
  map.push([0.5, 0.5]) // 104 (not detected)
  map.push([0.5667, 0.7573]) // 105
  map.push([0.8227, 0.5085]) // 106
  map.push([0.5796, 0.7573]) // 107
  map.push([0.5, 0.5]) // 108 (not detected)
  map.push([0.5, 0.5]) // 109 (not detected)
  map.push([0.2372, 0.6472]) // 110
  map.push([0.5, 0.5]) // 111 (not detected)
  map.push([0.8215, 0.5085]) // 112
  map.push([0.5, 0.5]) // 113 (not detected)
  map.push([0.1235, 0.6528]) // 114
  map.push([0.8227, 0.5080]) // 115
  map.push([0.5, 0.5]) // 116 (not detected)
  map.push([0.5, 0.5]) // 117 (not detected)
  map.push([0.5, 0.5]) // 118 (not detected)
  map.push([0.5, 0.5]) // 119 (not detected)
  map.push([0.0620, 0.5427]) // 120
  map.push([0.5, 0.5]) // 121 (not detected)
  map.push([0.0657, 0.5080]) // 122
  map.push([0.0476, 0.5839]) // 123
  map.push([0.0767, 0.5191]) // 124
  map.push([0.1034, 0.5312]) // 125
  map.push([0.1276, 0.5462]) // 126
  map.push([0.1518, 0.5085]) // 127
  map.push([0.1937, 0.5342]) // 128
  map.push([0.2023, 0.5417]) // 129
  map.push([0.2306, 0.5131]) // 130
  map.push([0.2581, 0.5296]) // 131
  map.push([0.2975, 0.5191]) // 132
  map.push([0.4731, 0.4452]) // 133
  map.push([0.3328, 0.5327]) // 134
  map.push([0.5, 0.5]) // 135 (not detected)
  map.push([0.3266, 0.5040]) // 136
  map.push([0.5, 0.5]) // 137 (not detected)
  map.push([0.5, 0.5]) // 138 (not detected)
  map.push([0.5, 0.5]) // 139 (not detected)
  map.push([0.9852, 0.4121]) // 140
  map.push([0.5, 0.5]) // 141 (not detected)
  map.push([0.8974, 0.6643]) // 142
  map.push([0.5, 0.5]) // 143 (not detected)
  map.push([0.5, 0.5]) // 144 (not detected)
  map.push([0.8203, 0.5070]) // 145
  map.push([0.7840, 0.5621]) // 146
  map.push([0.8203, 0.5070]) // 147
  map.push([0.1190, 0.4719]) // 148
  map.push([0.8223, 0.5085]) // 149
  map.push([0.0735, 0.4437]) // 150
  map.push([0.5, 0.5]) // 151 (not detected)
  map.push([0.8215, 0.5070]) // 152
  map.push([0.4924, 0.4362]) // 153
  map.push([0.0940, 0.4497]) // 154
  map.push([0.1059, 0.4216]) // 155
  map.push([0.5, 0.5]) // 156 (not detected)
  map.push([0.1531, 0.4256]) // 157
  map.push([0.1826, 0.4422]) // 158
  map.push([0.2208, 0.4432]) // 159
  map.push([0.2409, 0.4407]) // 160
  map.push([0.2762, 0.4392]) // 161
  map.push([0.2959, 0.4392]) // 162
  map.push([0.3045, 0.4573]) // 163
  map.push([0.3192, 0.4241]) // 164
  map.push([0.8215, 0.5070]) // 165
  map.push([0.2868, 0.4513]) // 166
  map.push([0.3008, 0.4508]) // 167
  map.push([0.5, 0.5]) // 168 (not detected)
  map.push([0.8223, 0.5055]) // 169
  map.push([0.2245, 0.4362]) // 170
  map.push([0.2072, 0.4307]) // 171
  map.push([0.2060, 0.4663]) // 172
  map.push([0.1641, 0.4236]) // 173
  map.push([0.5654, 0.7558]) // 174
  map.push([0.5, 0.5]) // 175 (not detected)
  map.push([0.1321, 0.3789]) // 176
  map.push([0.5, 0.5]) // 177 (not detected)
  map.push([0.1050, 0.3894]) // 178
  map.push([0.0804, 0.4030]) // 179
  map.push([0.1038, 0.3819]) // 180
  map.push([0.0870, 0.3623]) // 181
  map.push([0.1075, 0.3759]) // 182
  map.push([0.1420, 0.3824]) // 183
  map.push([0.1592, 0.3804]) // 184
  map.push([0.1888, 0.3623]) // 185
  map.push([0.2146, 0.3759]) // 186
  map.push([0.2515, 0.3653]) // 187
  map.push([0.2675, 0.3593]) // 188
  map.push([0.4941, 0.4407]) // 189
  map.push([0.4620, 0.4693]) // 190
  map.push([0.2971, 0.3889]) // 191
  map.push([0.5572, 0.3965]) // 192
  map.push([0.2495, 0.3975]) // 193
  map.push([0.2429, 0.4030]) // 194
  map.push([0.5, 0.5]) // 195 (not detected)
  map.push([0.5, 0.5]) // 196 (not detected)
  map.push([0.5, 0.5]) // 197 (not detected)
  map.push([0.1732, 0.3829]) // 198
  map.push([0.1350, 0.3910]) // 199
  map.push([0.5749, 0.7533]) // 200
  map.push([0.1165, 0.3633]) // 201
  map.push([0.1215, 0.3578]) // 202
  map.push([0.1502, 0.3518]) // 203
  map.push([0.8207, 0.5055]) // 204
  map.push([0.5, 0.5]) // 205 (not detected)
  map.push([0.2171, 0.3070]) // 206
  map.push([0.2405, 0.3367]) // 207
  map.push([0.2684, 0.3241]) // 208
  map.push([0.2774, 0.3367]) // 209
  map.push([0.2831, 0.3352]) // 210
  map.push([0.8211, 0.5050]) // 211
  map.push([0.5, 0.5]) // 212 (not detected)
  map.push([0.2442, 0.3457]) // 213
  map.push([0.8207, 0.5045]) // 214
  map.push([0.2503, 0.3879]) // 215
  map.push([0.2195, 0.3437]) // 216
  map.push([0.2023, 0.3387]) // 217
  map.push([0.5, 0.5]) // 218 (not detected)
  map.push([0.1637, 0.3487]) // 219
  map.push([0.5, 0.5]) // 220 (not detected)
  map.push([0.8203, 0.5055]) // 221
  map.push([0.0960, 0.2960]) // 222
  map.push([0.1186, 0.3216]) // 223
  map.push([0.1186, 0.2673]) // 224
  map.push([0.1247, 0.2839]) // 225
  map.push([0.1420, 0.2779]) // 226
  map.push([0.1604, 0.2799]) // 227
  map.push([1.0000, 0.5357]) // 228
  map.push([0.2121, 0.2372]) // 229
  map.push([0.2335, 0.2628]) // 230
  map.push([0.5, 0.5]) // 231 (not detected)
  map.push([0.5929, 0.5638]) // 232
  map.push([0.2897, 0.2643]) // 233
  map.push([0.2922, 0.2704]) // 234
  map.push([0.8195, 0.5050]) // 235
  map.push([0.5, 0.5]) // 236 (not detected)
  map.push([0.5, 0.5]) // 237 (not detected)
  map.push([0.8203, 0.5050]) // 238
  map.push([0.5, 0.5]) // 239 (not detected)
  map.push([0.8215, 0.5025]) // 240
  map.push([1.0000, 0.5407]) // 241
  map.push([0.1789, 0.3005]) // 242
  map.push([0.8215, 0.5055]) // 243
  map.push([0.5, 0.5]) // 244 (not detected)
  map.push([0.1260, 0.2613]) // 245
  map.push([0.1260, 0.2342]) // 246
  map.push([0.1604, 0.2302]) // 247
  map.push([0.1637, 0.2161]) // 248
  map.push([0.1715, 0.2367]) // 249
  map.push([0.2195, 0.2005]) // 250
  map.push([0.2343, 0.2221]) // 251
  map.push([0.2651, 0.2206]) // 252
  map.push([0.8215, 0.5055]) // 253
  map.push([0.2540, 0.2598]) // 254
  map.push([0.8277, 0.5533]) // 255
  map.push([0.8199, 0.5050]) // 256
  map.push([0.5, 0.5]) // 257 (not detected)
  map.push([0.8281, 0.5538]) // 258
  map.push([0.5, 0.5]) // 259 (not detected)
  map.push([0.8293, 0.5513]) // 260
  map.push([0.2060, 0.2312]) // 261
  map.push([0.1875, 0.2538]) // 262
  map.push([0.1572, 0.2613]) // 263
  map.push([0.1358, 0.2382]) // 264
  map.push([0.8026, 0.3819]) // 265
  map.push([0.5, 0.5]) // 266 (not detected)
  map.push([0.0985, 0.2101]) // 267
  map.push([0.1260, 0.1975]) // 268
  map.push([0.1629, 0.2492]) // 269
  map.push([0.1764, 0.2236]) // 270
  map.push([0.1863, 0.2181]) // 271
  map.push([0.2245, 0.2070]) // 272
  map.push([0.2474, 0.1789]) // 273
  map.push([0.5, 0.5]) // 274 (not detected)
  map.push([0.2589, 0.2085]) // 275
  map.push([0.5, 0.5]) // 276 (not detected)
  map.push([0.5, 0.5]) // 277 (not detected)
  map.push([0.5, 0.5]) // 278 (not detected)
  map.push([0.5753, 0.7528]) // 279
  map.push([0.1678, 0.2055]) // 280
  map.push([0.5, 0.5]) // 281 (not detected)
  map.push([0.1457, 0.1543]) // 282
  map.push([0.1407, 0.1558]) // 283
  map.push([0.1789, 0.1784]) // 284
  map.push([0.1912, 0.1633]) // 285
  map.push([0.1990, 0.1704]) // 286
  map.push([0.2294, 0.1603]) // 287
  map.push([0.5, 0.5]) // 288 (not detected)
  map.push([0.5, 0.5]) // 289 (not detected)
  map.push([0.5, 0.5]) // 290 (not detected)
  map.push([0.5, 0.5]) // 291 (not detected)
  map.push([0.1715, 0.1437]) // 292
  map.push([0.5, 0.5]) // 293 (not detected)
  map.push([0.4936, 0.4347]) // 294
  map.push([0.2085, 0.0653]) // 295
  map.push([0.2220, 0.0698]) // 296
  map.push([0.2339, 0.0538]) // 297
  map.push([0.2355, 0.0246]) // 298
  map.push([0.2060, 0.0000]) // 299
  return map
}
